name: Generate JSDoc

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: .
          output_dir: ./out
